server:
  port: 9090
spring:
  application:
    name: video-api
  datasource:
    url: jdbc:postgresql://localhost:5432/video_api
    username: postgres
    password: postgres
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  rabbitmq:
    addresses: amqp://localhost:5672
    username: guest
    password: guest
    listener:
      simple:
        default-requeue-rejected: false
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

application:
  queue:
    videoReceived:
      name: video_received
    videoStatusChanged:
      name: video_status_changed
  storage:
    fileSystem:
      active: true
      videoDirectory: ${user.home}/video_storage/video
      thumbnailDirectory: ${user.home}/video_storage/thumbnail
