apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: video-api
spec:
  hosts:
    - "*"
  gateways:
    - hack-g13
  http:
    - match:
        - uri:
            exact: /video
        - uri:
            prefix: /video/
      rewrite:
        uri: /
      route:
        - destination:
            host: video-api.default.svc.cluster.local
            port:
              number: 80
